context:
  version: "1.5.18"

package:
  name: sails
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sails/-/sails-${{ version }}.tgz
  sha256: 36c6a524606d898cefc7832c294b928ae68d7424848b67e2c57cf54381e83d0e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sails --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: API-driven framework for building realtime apps, using MVC conventions (based on Express and Socket.io)
  homepage: https://sailsjs.com/
  repository: https://github.com/balderdashy/sails

extra:
  recipe-maintainers:
    - danielnachun
