context:
  version: "1.5.14"

package:
  name: sails
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sails/-/sails-${{ version }}.tgz
  sha256: 610a3fd6c47c8b8c68ee79e1ab3680a4d6cd7dcf90a39ac84be59afe0fc26cbd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sails --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: API-driven framework for building realtime apps, using MVC conventions (based on Express and Socket.io)
  homepage: https://sailsjs.com/
  repository: https://github.com/balderdashy/sails

extra:
  recipe-maintainers:
    - danielnachun
